python-engineer/third-stage-website-building-and-flask/flask-ask-answer-system/qa/views.py
from flask import render_template, Blueprint, request

from models import Question

qa = Blueprint('qa', __name__, template_folder='templates', static_folder='../assets')


@qa.route('/')
def index():
    """ 首页 """
    return render_template('index.html')


@qa.route('/follow')
def follow():
    """ 关注 """
    per_page = 20  # 每页的数据量
    page = int(request.args.get('page', 1))
    page_data = Question.query.filter_by(is_valid=True).paginate(page=page, per_page=per_page)
    return render_template('follow.html', page_data=page_data)


@qa.route('/write')
def write():
    """ 写文章，提问 """
    return render_template('write.html')


@qa.route('/detail/<int:q_id>')
def detail(q_id):
    """ 详情页 """
    return render_template('detail.html')

python-engineer/third-stage-website-building-and-flask/flask-ask-answer-system/qa/templates/follow.html
{% extends 'base-layout.html' %}
{% block title %}
    {{ super() }} - 首页
{% endblock %}
{% block header %}
    <link rel="stylesheet" href="../../assets/style/index.css">
{% endblock %}

{% block content %}

<div class="layout-main">
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <!-- 消息通知区域 -->
                <div class="alert alert-warning alert-dismissible fade in" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                            aria-hidden="true">×</span></button>
                    <strong>你好，张三!</strong> 欢迎登陆在线问答系统
                </div>
                <!-- // 消息通知区域 -->
                <!-- banner图 -->
                <div id="id-index-banner" class="carousel slide" data-ride="carousel">
                    <!-- Wrapper for slides -->
                    <div class="carousel-inner" role="listbox">
                        <div class="item active">
                            <img class="img-responsive" src="../../assets/home/banner/banner1.jpg" alt="banner图">
                        </div>
                        <div class="item">
                            <img class="img-responsive" src="../../assets/home/banner/banner1.jpg" alt="banner图">
                        </div>
                    </div>

                    <!-- Controls -->
                    <a class="left carousel-control" href="#id-index-banner" role="button" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" href="#id-index-banner" role="button" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
                <!-- //banner图 -->
                <!-- 分类菜单 -->
                <div class="cls-menu-ls">
                    <a href="{{ url_for('qa.index') }}">推荐</a>
                    <a href="{{ url_for('qa.follow') }}" class="active">关注</a>
                    <a href="#">热榜</a>
                </div>
                <!-- //分类菜单 -->
                <!-- 问题列表 -->
                <div class="qa-ls">
                    {% for question in page_data.items %}
                    <div class="qa-item">
                        <a href="{{ url_for('qa.detail', q_id=question.id) }}"
                           class="title">{{ question.title }}</a>
                        <div class="desc">
                            {% if question.img %}
                                <div class="left">
                                    <img src="{{ question.img }}" alt="" srcset="">
                                </div>
                            {% endif %}
                            <div class="right">
                                <div class="show-desc">{{ question.desc|d('暂无描述', True) }}
                                    <span class="more">阅读原文<i class="glyphicon glyphicon-menu-down"></i></span>
                                </div>
                                <div class="show-all hidden">
                                    {% autoescape false %}
                                    {{ question.content|safe }}
                                    {% endautoescape %}
                                    <span class="more">收起<i class="glyphicon glyphicon-menu-up"></i></span>
                                </div>
                            </div>
                        </div>
                        <div class="qa-footer">
                            <div>
                                <button type="button" class="btn btn-info btn-sm">关 注</button>
                            </div>
                            <div class="txt-menu"><i
                                    class="glyphicon glyphicon-comment"></i> {{ question.comment_count }} 条评论
                            </div>
                            <div class="txt-menu"><i class="glyphicon glyphicon-send"></i>分享</div>
                            <div class="txt-menu"><i class="glyphicon glyphicon-flag"></i>举报</div>
                            <div class="txt-menu btn-group">
                                <i class="glyphicon glyphicon-option-horizontal dropdown-toggle"
                                   data-toggle="dropdown"
                                   aria-haspopup="true" aria-expanded="false"></i>
                                <ul class="dropdown-menu">
                                    <li><a href="#">不感兴趣</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-3">
                <!-- 右侧菜单 -->
                <div class="right-menu-box box-wrap">
                    <a href="#" class="menu-item">
                        <i class="glyphicon glyphicon-plus"></i>
                        <span>写回答</span>
                    </a>
                    <a href="write.html" class="menu-item">
                        <i class="glyphicon glyphicon-pencil"></i>
                        <span>写文章</span>
                    </a>
                    <a href="#" class="menu-item">
                        <i class="glyphicon glyphicon-ok"></i>
                        <span>些想法</span>
                    </a>
                    <a href="#" class="menu-item">
                        <i class="glyphicon glyphicon-play-circle"></i>
                        <span>发视频</span>
                    </a>
                    <a href="#" class="menu-item">
                        <i class="glyphicon glyphicon-adjust"></i>
                        <span>稍后答</span>
                    </a>
                    <a href="#" class="menu-item">
                        <i class="glyphicon glyphicon-file"></i>
                        <span>草稿箱</span>
                    </a>
                </div>
                <!-- 创作者入口 -->
                <div class="right-creater-box box-wrap">
                    <a href="#" class="menu-item">
                        <div class="left">
                            <i class="glyphicon glyphicon-user"></i>
                            <span>草稿箱</span>
                        </div>
                        <div class="right">
                            <span>去开通</span>
                            <i class="glyphicon glyphicon-menu-right"></i>
                        </div>
                    </a>
                </div>
                <!-- 彩色菜单入口 -->
                <div class="right-menu-box box-wrap">
                    <a href="#" class="menu-item menu-live">
                        <i class="glyphicon glyphicon-plus"></i>
                        <span>Live</span>
                    </a>
                    <a href="#" class="menu-item menu-store">
                        <i class="glyphicon glyphicon-pencil"></i>
                        <span>书店</span>
                    </a>
                    <a href="#" class="menu-item menu-table">
                        <i class="glyphicon glyphicon-ok"></i>
                        <span>圆桌</span>
                    </a>
                    <a href="#" class="menu-item menu-special">
                        <i class="glyphicon glyphicon-play-circle"></i>
                        <span>专栏</span>
                    </a>
                    <a href="#" class="menu-item menu-consult">
                        <i class="glyphicon glyphicon-adjust"></i>
                        <span>付费咨询</span>
                    </a>
                    <a href="#" class="menu-item menu-wiki">
                        <i class="glyphicon glyphicon-file"></i>
                        <span>百科</span>
                    </a>
                </div>
                <!-- // 彩色菜单入口 -->
                <!-- 我的入口 -->
                <div class="right-mine-box box-wrap">
                    <a href="#" class="menu-item">
                        <div class="left">
                            <i class="glyphicon glyphicon-heart"></i>
                            <span>我的收藏</span>
                        </div>
                        <div class="right">
                            <span>0</span>
                        </div>
                    </a>
                    <a href="#" class="menu-item">
                        <div class="left">
                            <i class="glyphicon glyphicon-question-sign"></i>
                            <span>我关注的问题</span>
                        </div>
                        <div class="right">
                            <span>28</span>
                        </div>
                    </a>
                    <a href="#" class="menu-item">
                        <div class="left">
                            <i class="glyphicon glyphicon-user"></i>
                            <span>我的邀请</span>
                        </div>
                        <div class="right">
                            <span>33</span>
                        </div>
                    </a>
                    <a href="#" class="menu-item">
                        <div class="left">
                            <i class="glyphicon glyphicon-yen"></i>
                            <span>我的余额</span>
                        </div>
                        <div class="right">
                        </div>
                    </a>
                    <a href="#" class="menu-item">
                        <div class="left">
                            <i class="glyphicon glyphicon-king"></i>
                            <span>站务中心</span>
                        </div>
                        <div class="right">
                        </div>
                    </a>
                    <a href="#" class="menu-item">
                        <div class="left">
                            <i class="glyphicon glyphicon-file"></i>
                            <span>版权服务中心</span>
                        </div>
                        <div class="right">
                        </div>
                    </a>
                </div>
                <!-- //我的入口 -->
                <!-- 右侧页脚 -->
                <div class="right-footer">
                    <a href="#">用户指南</a><span class="dot">·</span>
                    <a href="#">用户使用协议</a><span class="dot">·</span>
                    <a href="#">用户隐私权政策</a>
                    <br/>
                    <a href="#">侵权举报</a><span class="dot">·</span>
                    <a href="#">网上有害信息举报专区</a>
                    <br/>
                    <a href="#">京ICP证 第10001000号</a>
                    <br/>
                    <a href="#">京ICP备 第10001000号</a>
                    <br/>
                    <a href="#">联系我们 &copy; 2020在线问答</a>
                </div>
                <!-- //右侧页脚 -->
            </div>
        </div>
    </div>
    <!-- // container -->
</div>

<!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
<script src="../../assets/plugins/jquery-3.4.1.min.js"></script>
<!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
<script src="../../assets/plugins/bootstrap/js/bootstrap.min.js"></script>
{% endblock %}
{% block js_inline %}
    // 点击，查看更多，把详细的那个p标签展示出来，把自己隐藏
    $('.show-desc').click(function () {
    $(this).addClass('hidden');
    $(this).next().removeClass('hidden')
    })
    $('.show-all').click(function () {
    $(this).addClass('hidden');
    $(this).prev().removeClass('hidden')
    })
{% endblock %}

python-engineer/third-stage-website-building-and-flask/flask-ask-answer-system/qa/templates/write.html
<!DOCTYPE html>
<html lang="zh-CN">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
  <title>在线问答系统-写文章</title>

  <!-- Bootstrap -->
  <link href="../../assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- HTML5 shim 和 Respond.js 是为了让 IE8 支持 HTML5 元素和媒体查询（media queries）功能 -->
  <!-- 警告：通过 file:// 协议（就是直接将 html 页面拖拽到浏览器中）访问页面时 Respond.js 不起作用 -->
  <!--[if lt IE 9]>
    <script src="../../assets/plugins/html5shiv.min.js"></script>
    <script src="../../assets/plugins/respond.min.js"></script>
    <![endif]-->

  <link rel="stylesheet" href="../../assets/style/common.css">
  <link rel="stylesheet" href="../../assets/style/write.css">
</head>

<body class="layout">
  <!-- 顶部导航 -->
  <div class="layout-header">
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#id-index-banner"
            aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="index.html">在线问答系统</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="id-index-banner">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">首页 <span class="sr-only">(current)</span></a></li>
            <li><a href="#">话题</a></li>
          </ul>
          <form class="navbar-form navbar-left">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="搜索话题">
            </div>
            <button type="submit" class="btn btn-default">搜索</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">提问</a></li>
            <li><a href="#">消息<span class="badge">4</span></a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                aria-expanded="false">个人中心 <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">我的主页</a></li>
                <li><a href="#">设置</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">退出</a></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </div>
  <!-- // 顶部导航 -->
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <form class="form-horizontal write-form">
          <div class="form-group">
            <button type="submit" class="btn btn-info pull-right">发布</button>
          </div>
          <div class="form-group">
            <label class="upload-file">
              <input type="file" accept=".jpeg, .jpg, .png">
              <i class="glyphicon glyphicon-camera"></i>
            </label>
          </div>
          <div class="form-group">
            <input type="text" class="form-control" placeholder="请输入标题（最多50个字）">
          </div>
          <div class="form-group">
            <input type="text" class="form-control" placeholder="输入标签，用,分隔">
          </div>
          <div class="form-group">
            <textarea class="form-control" rows="5" placeholder="简述"></textarea>
          </div>
          <div class="form-group">
            <textarea class="form-control" rows="10" placeholder="请输入正文"></textarea>
          </div>
        </form>
      </div>
    </div>
  </div>

  <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
  <script src="../../assets/plugins/jquery-3.4.1.min.js"></script>
  <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
  <script src="../../assets/plugins/bootstrap/js/bootstrap.min.js"></script>
  <script>
    $(function () {
      // 文件选择后，在浏览器中预览
      $('input[type=file]').change(function () {
        var file = this.files[0];
        var reader = new FileReader();
        reader.onload = function () {
          $('.upload-file').css('background-image', 'url(' + reader.result + ')')
        }
        reader.readAsDataURL(file);
      })
    })
  </script>
</body>

</html>